#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const mongoose = require("mongoose");

const DEFAULT_COUNT = 1000;
const DEFAULT_DB_NAME = "newsforge";
const BATCH_SIZE = 100;

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return;
  }

  const content = fs.readFileSync(filePath, "utf8");
  const lines = content.split(/\r?\n/);

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }

    const separatorIndex = line.indexOf("=");
    if (separatorIndex < 1) {
      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    if (!key || process.env[key] !== undefined) {
      continue;
    }

    let value = line.slice(separatorIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    process.env[key] = value;
  }
}

function loadEnv() {
  const projectRoot = process.cwd();
  const envFiles = [".env.local", ".env"];

  for (const envFile of envFiles) {
    loadEnvFile(path.join(projectRoot, envFile));
  }
}

function parseCountArg() {
  const countFlag = process.argv.find((arg) => arg.startsWith("--count="));
  const rawValue = countFlag ? countFlag.split("=")[1] : undefined;
  const parsed = Number.parseInt(rawValue || `${DEFAULT_COUNT}`, 10);

  if (!Number.isFinite(parsed) || parsed <= 0) {
    throw new Error("Invalid --count value. Use a positive integer.");
  }

  return parsed;
}

function toObjectId(value) {
  return new mongoose.Types.ObjectId(value);
}

async function ensureCategory(db, now) {
  const categories = db.collection("categories");
  await categories.updateOne(
    { slug: "bulk-seeded" },
    {
      $setOnInsert: {
        name: "Bulk Seeded",
        slug: "bulk-seeded",
        description: "Category used for generated bulk seed content.",
        createdAt: now,
        updatedAt: now
      }
    },
    { upsert: true }
  );

  return categories.findOne({ slug: "bulk-seeded" }, { projection: { _id: 1 } });
}

async function ensureTag(db, now) {
  const tags = db.collection("tags");
  await tags.updateOne(
    { slug: "bulk-generated" },
    {
      $setOnInsert: {
        name: "Bulk Generated",
        slug: "bulk-generated",
        createdAt: now,
        updatedAt: now
      }
    },
    { upsert: true }
  );

  return tags.findOne({ slug: "bulk-generated" }, { projection: { _id: 1 } });
}

async function ensureAuthor(db, now) {
  const authors = db.collection("authors");
  const email = "bulk-seed@newsforge.local";

  await authors.updateOne(
    { email },
    {
      $setOnInsert: {
        name: "Bulk Seed Writer",
        slug: "bulk-seed-writer",
        email,
        bio: "Autogenerated author for bulk insert scripts.",
        avatarUrl: "/placeholder-news.svg",
        createdAt: now,
        updatedAt: now
      }
    },
    { upsert: true }
  );

  return authors.findOne({ email }, { projection: { _id: 1 } });
}

function longTitle(index) {
  const i = index + 1;
  return `Comprehensive Regional Policy Briefing ${i}: Strategic Infrastructure Planning, Economic Transition Signals, Civic Impact Outlook, and Long-Range Governance Scenarios`;
}

function longParagraph(index, paragraphIndex) {
  const i = index + 1;
  const p = paragraphIndex + 1;

  return `Post ${i}, section ${p}: This extended report examines municipal planning timelines, labor market adaptation patterns, public finance pressures, climate resilience requirements, and institutional accountability frameworks in one continuous narrative. Editors outline stakeholder positions, cite implementation constraints, compare legacy policy outcomes, and document measurable milestones so newsroom teams can evaluate operational risk, social impact, and long-horizon sustainability with clear evidence and repeatable assumptions.`;
}

function buildHtmlAndJson(title, index) {
  const paragraphs = Array.from({ length: 8 }, (_, paragraphIndex) => longParagraph(index, paragraphIndex));

  const html = [
    `<h2>${title}</h2>`,
    ...paragraphs.map((text) => `<p>${text}</p>`)
  ].join("\n");

  const json = {
    type: "doc",
    content: [
      {
        type: "heading",
        attrs: { level: 2 },
        content: [{ type: "text", text: title }]
      },
      ...paragraphs.map((text) => ({
        type: "paragraph",
        content: [{ type: "text", text }]
      }))
    ]
  };

  return { html, json };
}

function buildDoc({
  index,
  runKey,
  now,
  siteUrl,
  categoryId,
  tagId,
  authorId
}) {
  const postNumber = index + 1;
  const title = longTitle(index);
  const slug = `bulk-post-${runKey}-${postNumber}`;
  const { html, json } = buildHtmlAndJson(title, index);

  const excerpt =
    `Detailed newsroom analysis ${postNumber}: policy execution risk, macroeconomic stress testing, regional governance tradeoffs, and evidence-led implementation priorities for long-form editorial coverage.`;

  const publishedAt = new Date(now.getTime() - index * 60_000);
  const scheduledFor = new Date(now.getTime() + (index + 1) * 60_000);

  return {
    _id: toObjectId(),
    title,
    slug,
    excerpt,
    content: {
      json,
      html
    },
    featuredImage: {
      originalUrl: "/placeholder-news.svg",
      optimizedUrl: "/placeholder-news.svg",
      thumbnailUrl: "/placeholder-news.svg",
      responsive: [
        { url: "/placeholder-news.svg", width: 480, height: 270 },
        { url: "/placeholder-news.svg", width: 960, height: 540 },
        { url: "/placeholder-news.svg", width: 1200, height: 675 }
      ],
      alt: `Illustrative editorial scene for autogenerated bulk post ${postNumber}`,
      width: 1200,
      height: 675
    },
    categoryId,
    tagIds: [tagId],
    authorId,
    status: "published",
    publishedAt,
    scheduledFor,
    seo: {
      metaTitle: `${title} | NewsForge`,
      metaDescription: excerpt,
      keywords: [
        "news analysis",
        "long form journalism",
        "policy brief",
        `bulk post ${postNumber}`
      ],
      canonicalUrl: `${siteUrl}/news/${slug}`
    },
    internalLinks: [
      {
        title: `Related context report ${postNumber}`,
        slug: `related-context-report-${postNumber}`,
        url: `${siteUrl}/news/related-context-report-${postNumber}`
      },
      {
        title: `Follow-up governance review ${postNumber}`,
        slug: `follow-up-governance-review-${postNumber}`,
        url: `${siteUrl}/news/follow-up-governance-review-${postNumber}`
      }
    ],
    createdAt: now,
    updatedAt: now
  };
}

async function main() {
  loadEnv();

  const count = parseCountArg();
  const mongoUri = process.env.MONGODB_URI;
  const dbName = process.env.MONGODB_DB || DEFAULT_DB_NAME;
  const siteUrl = (process.env.SITE_URL || "http://localhost:3000").replace(/\/$/, "");

  if (!mongoUri) {
    throw new Error("Missing MONGODB_URI. Set it in .env.local or .env");
  }

  const now = new Date();
  const runKey = `${now.getTime()}`;

  await mongoose.connect(mongoUri, { dbName });
  const db = mongoose.connection.db;
  if (!db) {
    throw new Error("Unable to access MongoDB database connection.");
  }

  const [category, tag, author] = await Promise.all([
    ensureCategory(db, now),
    ensureTag(db, now),
    ensureAuthor(db, now)
  ]);

  if (!category?._id || !tag?._id || !author?._id) {
    throw new Error("Failed to ensure required category/tag/author records.");
  }

  const categoryId = toObjectId(category._id);
  const tagId = toObjectId(tag._id);
  const authorId = toObjectId(author._id);

  let insertedCount = 0;
  const articles = db.collection("articles");

  for (let start = 0; start < count; start += BATCH_SIZE) {
    const end = Math.min(start + BATCH_SIZE, count);
    const docs = [];
    for (let index = start; index < end; index += 1) {
      docs.push(
        buildDoc({
          index,
          runKey,
          now,
          siteUrl,
          categoryId,
          tagId,
          authorId
        })
      );
    }

    const result = await articles.insertMany(docs, { ordered: false });
    insertedCount += result.insertedCount || 0;
    process.stdout.write(`Inserted batch ${start + 1}-${end}\n`);
  }

  process.stdout.write(`Seed complete: inserted ${insertedCount} posts into "${dbName}.articles"\n`);
  await mongoose.disconnect();
}

main().catch(async (error) => {
  process.stderr.write(`Seed failed: ${error.message}\n`);
  try {
    await mongoose.disconnect();
  } catch {
    // no-op
  }
  process.exit(1);
});
